/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:b7ab0589-1c81-4377-940e-8c8ebfde88f2",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_NMDwLp7HH",
    "aws_user_pools_web_client_id": "10ebmpfmn033hnntcsrl2r9q0o",
    "oauth": {}
};


export default awsmobile;
